base: apu_diff_base.yaml

training:
  batch_size: 16
  stage1_epochs: 2
  stage1_improve_weight: 10.0

checkpoint_dir: checkpoints/sportsmot_smoke
feature_dir: datasets/sportsmot_train_gt_fastreid
val_feature_dir: datasets/sportsmot_val_gt_fastreid
sequences:
  - v_-6Os86HzwCs_c007
val_sequences:
  - v_00HRwkvvjtQ_c001
